### ISSUE TITLE
dce-system/insight chart has repeated app.kubernetes.io/name field in multiple templates

### ISSUE THREAD

**Issue by DonaldKellett** [DaoCloud/public-helm-charts-mirror#47]
`dce-system/insight` chart has repeated `app.kubernetes.io/name` field in multiple templates which causes HelmRelease reconciliation failures with [Flux v2](https://github.com/fluxcd/flux2) as shown in the screenshot below:

![2023-11-07 16_43_58-donaldleung@ESPF3QDR0B_ ~](https://github.com/DaoCloud/public-helm-charts-mirror/assets/7777884/7c754735-8299-4a2f-b5f4-3a002d6d5680)

Furthermore, this issue is reproducible with the default `values.yaml` provided by the chart itself so not specific to a particular `values.yaml` configuration.

## Chart details

- Repository: `dce-system` \(`https://release.daocloud.io/chartrepo/system`\)
- Chart name: `insight`
- Chart version: `0.21.1` (affects `0.19.x` as well)

## Steps to reproduce

```bash
helm repo add dce-system https://release.daocloud.io/chartrepo/system
helm repo update
helm pull --version 0.21.1 dce-system/insight --untar
helm template insight insight/ --show-only templates/runbooks/serviceaccount.yaml | yq '.metadata.labels'
```

Output:

```yaml
app.kubernetes.io/name: insight-runbook
helm.sh/chart: insight-0.21.1
app.kubernetes.io/name: insight
app.kubernetes.io/instance: insight
app.kubernetes.io/version: "0.21.1"
app.kubernetes.io/managed-by: Helm
```

As can be seen, the field `app.kubernetes.io/name` is defined twice.

This issue occurs multiple times throughout the chart - please refer to the attachment below for the full output of `helm template`.

[insight-template.yaml.txt](https://github.com/DaoCloud/public-helm-charts-mirror/files/13278236/insight-template.yaml.txt)
