### ISSUE TITLE
dce-system/kpanda chart has repeated app field in template charts/clusterpedia/templates/clustersynchro-manager-deployment.yaml

### ISSUE THREAD

**Issue by DonaldKellett** [DaoCloud/public-helm-charts-mirror#50]
`dce-system/kpanda` chart has repeated `app` field in template `charts/clusterpedia/templates/clustersynchro-manager-deployment.yaml` which causes HelmRelease reconciliation failures with [Flux v2](https://github.com/fluxcd/flux2) as shown in the screenshot below:

![2023-11-08 11_09_31-donaldleung@ESPF3QDR0B_ ~](https://github.com/DaoCloud/public-helm-charts-mirror/assets/7777884/4bd023ed-4103-46cd-b40d-862fd5733628)

## Chart details

- Repository: `dce-system` \(`https://release.daocloud.io/chartrepo/system`\)
- Chart name: `kpanda`
- Chart version: `0.22.1`

## Steps to reproduce

```bash
helm repo add dce-system https://release.daocloud.io/chartrepo/system
helm repo update
helm pull --version 0.22.1 dce-system/kpanda --untar
helm template kpanda kpanda/ --show-only charts/clusterpedia/templates/clustersynchro-manager-deployment.yaml | yq '.spec.template.metadata.labels'
```

Output \(notice the duplicate `app` field\):

```yaml
app.kubernetes.io/name: clusterpedia
helm.sh/chart: clusterpedia-1.7.2
app.kubernetes.io/instance: kpanda
app.kubernetes.io/managed-by: Helm
app: kpanda-clusterpedia-clustersynchro-manager
app: kpanda-clusterpedia-clustersynchro-manager
sidecar.istio.io/inject: "true"
```

Please find the full template output as attached below for your reference.

[kpanda-template.yaml.txt](https://github.com/DaoCloud/public-helm-charts-mirror/files/13291637/kpanda-template.yaml.txt)
